[phases.setup]
aptPkgs = ["ffmpeg", "imagemagick"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "export FFMPEG_PATH=/usr/bin/ffmpeg && export MAGICK_PATH=/usr/bin/convert && uvicorn api_server:app --host 0.0.0.0 --port $PORT"
