[phases.setup]
nixPkgs = ["python311"]
aptPkgs = ["ffmpeg", "imagemagick"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn api_server:app --host 0.0.0.0 --port $PORT"
